package de.rpg.character.ausruestung.spezifikation;

public enum AusruestungsTyp {
	FEUERWAFFEN_MUNITION, FEUER_WAFFE, FEUER_WAFFE_ZUBEHOER, NAHKAMPF_WAFFE, PROJEKTIL_WAFFE, RAKETE, GRANATE, 
	SPRENGSTOFF, KLEIDUNG, SICHT_VERSTAERKER, KOMMUNIKATION, UEBERWACHUNGSSYSTEME, ANTI_UEBERWACHUNGSSYSTEME,
	SICHERHEITSTECHNIK, UEBERLEBENSAUSRUESTUNG, WERKZEUG, UNTERHALTUNG, ELEKTRONIK, CYBERWARE;
}
