package de.rpg.character.ausruestung.spezifikation;

public enum FahrzeugKategorie {
	AUTO, MOTORRAD, HOVERCRAFT, MOTORBOOT, SEGELBOOT, TRAGFLAECHEN_FLUGZEUG, ROTOR_FLUGZEUG,
	MILITAERISCH_TRAGFLAECHEN, MILITAERISCH_THUNDERBIRD, SICHERHEIT_AUTO, SICHERHEIT_HOVERCRAFT,
	SICHERHEIT_MOTORBOOT, SICHERHEIT_ROTOR, SICHERHEIT_ROTOR_DRONE, SICHERHEIT_AUTO_DRONE;
}
