package de.rpg.character.ausruestung.spezifikation;

public enum ModTyp {
	RUECKSTOSS, GEWICHT, TARNSTUFE, ENTDECKUNGSPROBE, VERGROESSERUNG, SICHT_RV, SICHT_IR, MINDESTWURF,
	GEHOER_HF, GEHOER_NF, ST, SCH, NAH_WAFFE, INI, AUSSCHLUSS, REA, KON_SOAK;
}
